version: "3.8"

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: develop
      MYSQL_USER: django
      MYSQL_PASSWORD: password
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    tty: true
    restart: "always"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
